@host = 12354

### GET TEST
GET http://localhost:{{host}}/api/togethers/5d21900d0b1d6d4cac321b79/events/

### GET TEST
GET http://localhost:{{host}}/api/togethers/5d21900d0b1d6d4cac321b79/events/5cfc926b78304a63749bc6d5

### GET 모임 대쉬보드 이벤트 가져오기 조건걸기 예
GET http://localhost:{{host}}/api/togethers/5d21900d0b1d6d4cac321b79/events/
    ?date=2019-06-09

### GET 모임 대쉬보드 이벤트 가져오기 조건걸기 예
GET http://localhost:{{host}}/api/togethers/5d21900d0b1d6d4cac321b79/events/
    ?startdate=2019-06-15
    &enddate=2019-06-21

### POST 벙 생성
POST http://localhost:{{host}}/api/togethers/5d21900d0b1d6d4cac321b79/events/
content-type: application/json

{
    "title" : "오늘 노가리 벙입니다",
    "categoryCode" : "5d2190b40b1d6d4cac321b7b",
    "locationCode" : "5cf38a4294371522a4c10144",
    "message" : "노가리 까러오세요~",
    "date": "{{$datetime '2019-09-010'}}",
    "togetherId": "5d21900d0b1d6d4cac321b79",
    "limit": 10
}

### PATCH 벙 수정
PATCH http://localhost:{{host}}/api/togethers/5cfc79afa210894244bc5334/events/5cfc9ac2a57c854be418e36e
content-type: application/json

{
    "message" : "그냥 아무나 영화보러오세요~",
    "date": "{{$datetime '2019-09-200'}}"
}

### DELETE 벙 삭제
DELETE http://localhost:{{host}}/api/togethers/5d21900d0b1d6d4cac321b79/events/5d54dd94cf10662e98251828


### POST 벙 참석하기
POST http://localhost:{{host}}/api/togethers/5d21900d0b1d6d4cac321b79/events/5d5ed3fc309f1e2998a79ad1/members/5d218f7c0b1d6d4cac321b77


### DELETE 벙 참석취소하기
DELETE http://localhost:{{host}}/api/togethers/5d21900d0b1d6d4cac321b79/events/5d5ed3fc309f1e2998a79ad1/members/5d218f7c0b1d6d4cac321b77

